Diagnosis manager implementation in the master
intelligent-machine-learning/dlrover pull request #1096
Opened 2024-04-25 03:52 UTC by samplise

### What changes were proposed in this pull request?

Implement the diagnosis manager in the master.

### Why are the changes needed?

The diagnosis manager is responsible for collecting diagnosis data from workers. Then it identifies and handles training faults.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Unit test.

2024-04-25 09:24 UTC, BalaBalaYi requested changes

2024-04-25 09:24 UTC, BalaBalaYi commented on dlrover/python/master/diagnosis/inferencechain/common.py
> +    for inference2 in inferences2:
```
inferences = list(set(inferences1 + inferences2))
```

2024-04-25 09:24 UTC, BalaBalaYi commented on dlrover/python/master/diagnosis/inferencechain/inference_chain.py
> +class InferenceChain:
Need annotations.

2024-04-25 09:24 UTC, BalaBalaYi commented on dlrover/python/master/diagnosis/inferencechain/inference_chain.py
> +                    new_infs.append(inference)
Why still append inference in 'catch'?

2024-04-25 09:24 UTC, BalaBalaYi commented on dlrover/python/master/diagnosis/inferencechain/inference_chain.py
> +            else:
Is there any possible 'has_new_inference' always false?

2024-04-25 20:41 UTC, samplise commented on dlrover/python/common/grpc.py
> -    timestamp: int = 0
Here I use `time.now().timestamp()` to get the timestamp that returns a float.

2024-04-25 20:54 UTC, samplise commented on dlrover/python/common/diagnosis.py
> +    def __init__(self, timestamp: float):
Currently those class definitions are not finalized. It is possible to modify the definition in the future.

2024-04-25 20:55 UTC, samplise commented on dlrover/python/common/diagnosis.py
> +    CHIPMETRICES = "chip_metrics"
Here chip metrics include temperature, utilization, etc. I think metrics are more accurate.

2024-04-25 20:56 UTC, samplise commented on dlrover/python/elastic_agent/datacollector/cuda_log_collector.py
> +        log = CudaLog(0)
It indicates the timestamp is assigned and should use current timestamp.

2024-04-26 02:43 UTC, BalaBalaYi commented on dlrover/python/common/grpc.py
> -    timestamp: int = 0
```time.now()``` -> ```datatime.now()``` ?

2024-04-29 04:38 UTC, samplise commented on dlrover/python/master/diagnosis/analyst.py
> +def register_problems() -> List[Inference]:
Yes. The diagnosis needs to check if there is any listed problem during training. This function is used to register those problems.

2024-04-29 04:39 UTC, samplise commented on dlrover/python/master/diagnosis/diagnosis.py
> +    def stop(self):
It is not a final implementation. The current version only reflects the design.

2024-04-29 04:46 UTC, samplise commented on dlrover/python/master/diagnosis/diagnosis.py
> +            time.sleep(180)
Sure. I plan to put it in the next pr.

2024-04-30 02:25 UTC, workingloong commented on dlrover/python/master/diagnosis/inferencechain/common.py
> +class Inference(object):
Use dataclass to wrap the `Inference`.

```Python
from dataclasses import dataclass

@dataclass
class Inference:
    name: str = ""
    attribute: str = ""
    description: str = ""
```

2024-04-30 05:53 UTC, workingloong commented on dlrover/python/master/diagnosis/inferencechain/inference_chain.py
> +                    print(operator)
Remove the line 46 and 48.

2024-04-30 06:09 UTC, workingloong approved these changes
LGTM

2024-05-06 02:28 UTC, BalaBalaYi approved these changes

2024-05-06 02:52 UTC, merged