Expose important event
intelligent-machine-learning/dlrover pull request #1203
Opened 2024-07-18 00:15 UTC by samplise

### What changes were proposed in this pull request?

Add API to expose important information.

### Why are the changes needed?

Users can understand the execution of training job in detail.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Unit test.

2024-08-07 02:49 UTC, workingloong commented on setup.py
> +    version="0.3.6.1rc0",
"0.3.6rc1" is better than "0.3.6.1rc0".

2024-08-07 06:50 UTC, BalaBalaYi requested changes

2024-08-07 06:50 UTC, BalaBalaYi commented on dlrover/python/master/elastic_training/rdzv_manager.py
> +                    "job rendezvous",
All the key metrics need to be defined as constant. Better use capital letter to define the metrics.

2024-08-07 06:50 UTC, BalaBalaYi commented on dlrover/python/master/monitor/speed_monitor.py
> +    def __init__(self, error_monitor: ErrorMonitor = None):
Why error_monitor in speed_monitor?  The implementation of this two monitor is parallel i think.

2024-08-07 06:50 UTC, BalaBalaYi commented on dlrover/python/master/node/dist_job_manager.py
> +            if self._error_monitor:
Should abstract this into a function:
```
def report_failure(self, node, restart_cnt, msg, level):
    if self._error_monitor:
        self._error_monitor.process_error(node, restart_cnt, msg, level)
```
To ignore if-else every where.

2024-08-07 07:02 UTC, BalaBalaYi commented on dlrover/python/master/monitor/error_monitor.py
> +        action: str,
Need to define a metric constant for all the event action.
e.g.
```
RDZV_PREFIX = "rdzv_"
RDZV_EVENT1 = RDZV_PREFIX + "event1"

WORKER_PREFIX = "worker_"
WORKER_CREATION = "WORKER_PREFIX" + "creation"
```

2024-08-07 07:11 UTC, BalaBalaYi commented on setup.py
> +    version="0.3.6.1rc0",
just 0.3.7

2024-08-08 02:11 UTC, BalaBalaYi approved these changes
LGTM

2024-08-08 03:03 UTC, merged