Job exit when all nodecheck failed
intelligent-machine-learning/dlrover pull request #1323
Opened 2024-11-06 13:13 UTC by majieyue

### What changes were proposed in this pull request?

exit job if all workers can't pass node check

### Why are the changes needed?

no need to re-check or try to fault tolerant this error

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

UT

2024-11-07 01:31 UTC, samplise commented on dlrover/python/master/node/dist_job_manager.py
> +            )
process_error(message=msg, level=...)

2024-11-07 02:02 UTC, BalaBalaYi requested changes

2024-11-07 02:02 UTC, BalaBalaYi commented on dlrover/python/master/node/dist_job_manager.py
> +    def is_all_workers_node_check_failed(self):
Better move this function into ```WorkerManager```. And work for 'AllReduceType' training only.

2024-11-07 11:50 UTC, workingloong commented on dlrover/python/master/node/dist_job_manager.py
> +                for _, node in self._job_nodes[NodeType.WORKER].items()
`for node in self._job_nodes[NodeType.WORKER].values()`

2024-11-08 09:45 UTC, BalaBalaYi commented on dlrover/python/master/node/worker.py
> +        nodes = self._job_context.job_nodes_by_type(NodeType.WORKER)
```nodes = self._get_nodes()```

2024-11-08 10:13 UTC, majieyue commented on dlrover/python/master/node/worker.py
> +        nodes = self._job_context.job_nodes_by_type(NodeType.WORKER)
done

2024-11-08 10:15 UTC, BalaBalaYi approved these changes
lgtm

2024-11-11 02:28 UTC, merged