Fix the issue that len(indices) and num_samples might not be equal
intelligent-machine-learning/dlrover pull request #1339
Opened 2024-11-15 12:47 UTC by sunjq1

### What changes were proposed in this pull request?

 Modified the definition of `total_size` in the `load_state_dict` function and the definition of `indices` in the `__iter__` function to ensure that `assert len(indices) == self.num_samples`.

### Why are the changes needed?

 In the previous ElasticDistributedSampler code, the issue where `completed_num` not being divisible by `num_replicas` could cause an `AssertionError` in the scenario of importing a checkpoint was not considered.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

UT and training test.

2024-11-19 08:53 UTC, BalaBalaYi requested changes
please add ut to cover the issue mentioned

2024-11-26 07:39 UTC, sunjq1 commented
> please add ut to cover the issue mentioned

 
since I adjusted the logic for splitting indices after loading the checkpoint, I corrected the num values in the UT file

2025-01-06 03:52 UTC, BalaBalaYi approved these changes
LGTM

2025-01-06 03:52 UTC, merged

2025-05-23 12:32 UTC, zhengchenyu commented on dlrover/trainer/tests/torch/elastic_sampler_test.py
> +        self.assertEqual(val, 66)
This should be caused by scaling. This unit-test tells us that data will be lost.