feat(model_zoo): add llama2 fsdp finetuning example
intelligent-machine-learning/dlrover pull request #565
Opened 2023-08-02 01:23 UTC by Major-333

### What changes were proposed in this pull request?

1. Added a model example for fine-tuning Llama2
2. Added a training image for building Llama2 fine-tuning
3. Added a job configuration example for Llama2 fine-tuning phase 2.

### Why are the changes needed?

Added a model example of fine-tuning the Llama2 model based on the FSDP training strategy.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Manual

2023-08-02 01:29 UTC, Major-333 commented
Documentation work is in progress.

2023-08-03 05:46 UTC, merlintang commented on model_zoo/pytorch/llama/configs/fsdp.py
> +
dont make blank line here

2023-08-03 05:46 UTC, merlintang commented on model_zoo/pytorch/llama/configs/fsdp.py
> +    optimizer: str= "AdamW"
does this configurable?

2023-08-03 05:46 UTC, merlintang commented on model_zoo/pytorch/llama/configs/peft.py
> +# Copyright (c) Meta Platforms, Inc. and affiliates.
does this ok?

2023-08-03 05:47 UTC, merlintang requested changes
can you split this pr into different parts? this would help us to review it.

2023-08-15 14:32 UTC, Major-333 commented
> 



> can you split this pr into different parts? this would help us to review it.

I'm really sorry. I didn't set up Github notifications to go to my primary email, so I missed many of your messages. I'll be closing this PR soon and will upload the changes in separate parts as per your request.

2023-08-15 14:32 UTC, closed without merging