doc(fsdp): add fsdp design doc
intelligent-machine-learning/dlrover pull request #620
Opened 2023-08-15 14:11 UTC by Major-333

2023 ospp design doc

2023-08-16 08:54 UTC, workingloong commented on docs/design/fsdp-design.md
> +随着大规模机器学习模型的持续增长，分布式训练已经成为该领域的核心技术。DLRover系统已展现出其在多个方面的优势，特别是在节点故障、资源动态分配和自动恢复等关键场景下。尽管PyTorch原生支持Fully Sharded Data Parallelism (FSDP) 策略，但DLRover作为一个天然的弹性训练系统，当面临动态的资源扩缩容和容错场景时，简单的使用PyTorch的FSDP可能会
列出来会导致什么问题。

2023-08-16 08:54 UTC, workingloong commented on docs/design/fsdp-design.md
> +1. **系统弹性与FSDP策略的结合**：虽然PyTorch提供了FSDP的支持，但在DLRover的弹性环境中，例如节点的动态扩缩容，需要更为深入的整合以确保FSDP策略的正常运作。
**FDSP策略应用在弹性训练**：DLRover 的弹性训练作业中，节点数量会发生变化导致 world size 变化，FSDP 需要能适应动态的  world size。

ps：我们列出的问题和调整要具体。

2023-08-16 08:54 UTC, workingloong commented on docs/design/fsdp-design.md
> +2. **确保训练的稳定性**：DLRover在弹性扩缩容和容错时，可能会面临因worldsize变化而导致的checkpoint加载问题。系统级别的FSDP支持可以确保这些场景下模型的稳定训练。
“可能会面临因worldsize变化而导致的checkpoint加载问题” 要说明会加载 checkpoint的具体问题。

FSDP 在 rank0_only=False时，加载checkpoint需要保证当前的 world size 和保持checkpoint 的 WORLD_SIZE 一致。然后弹性容错场景下，WORLD_SIZE 可能不一致。

2023-08-16 08:54 UTC, workingloong commented on docs/design/fsdp-design.md
> +1. **模型恢复的复杂性**：由于DLRover的弹性特性，如何在worldsize发生变化时，基于checkpoint准确恢复模型状态，成为了一个关键技术问题。
worldsize -> world size 。

“基于checkpoint准确恢复模型状态” 这句话体现不出“复杂性” 这三个词。

要说明：如果 world size 发生变化，FSDP 恢复 checkpoint 时需要对参数根据当前 world size 进行 reshard。这需要改变 FSDP 保持 checkpoint 会恢复 checkpoint 的机制。

2023-08-16 08:54 UTC, workingloong commented on docs/design/fsdp-design.md
> +将主要对 DLRover 系统中的 ElasticTrainer 模块、Master 模块进行修改。ElasticTrainer 相当于是运行在 worker pod 中的 Agent，因此将主要修改这个模块使其能够支持在fsdp训练策略下，没过一段step或者epoch后保存模型分片，然后在pod数量发生变化时reaload 模型和优化器状态的分片。修改Master主要是因为Worker po
“ElasticTrainer 相当于是运行在 worker pod 中的 Agent” ->  "ElasticTrainer 是管理模型训练的 manager"。 agent 是用来管理训练子进程的，不是管理model,optimizer 和training loop 的。

“没过一段step” -> "每过一段 step"

“修改Master主要是因为Worker pod是由master拉起，因此我们需要在master创建 Worker 这部分代码中进行修改，使其能够传入必要的环境变量等”。 要传什么环境变量？为什么？

2023-08-16 08:54 UTC, workingloong commented on docs/design/fsdp-design.md
> +- **prepare 函数的修改**：初始化时需要检查是否需要先load模型和优化器状态参数分片，如果分片和当前worker数不一致需要reshard load
句子结尾的标点符号。

2023-08-16 08:54 UTC, workingloong commented on docs/design/fsdp-design.md
> +3. load_from_checkpoint：bool，从环境变量中获取，默认值是 False。当为 True 时，将在 Elastic Trainer 的 prepare 函数中，load checkpoint，更新 model 和 optimizer 的 state。
不用从环境变量取，让用户自己配置就行了。还有个方式，检查 `checkpoint_path` 下是否 checkpoint 文件，有则加载，没有则不加载。

2023-08-16 08:54 UTC, workingloong commented on docs/design/fsdp-design.md
> +2. 两个环境变量：USE_FSDP 和 SHARED_STORAGE_PATH
这些都让用户在训练脚本里配置吧

2023-08-20 20:29 UTC, merlintang requested changes
english is better

2023-08-21 00:58 UTC, Major-333 commented on docs/design/fsdp-design.md
> +						    - name: USE_FSDP
是指volumeMounts和volumes吗

2023-08-21 01:35 UTC, Major-333 commented on docs/design/fsdp-design.md
> +将主要对 DLRover 系统中的 ElasticTrainer 模块、Master 模块进行修改。ElasticTrainer 相当于是运行在 worker pod 中的 Agent，因此将主要修改这个模块使其能够支持在fsdp训练策略下，没过一段step或者epoch后保存模型分片，然后在pod数量发生变化时reaload 模型和优化器状态的分片。修改Master主要是因为Worker po
现在不需要修改Master了

2023-08-28 10:33 UTC, workingloong commented on docs/design/fsdp-design.md
> +随着大规模机器学习模型的持续增长，分布式训练已经成为该领域的核心技术。DLRover 系统已展现出其在多个方面的优势，特别是在节点故障、资源动态分配和自动恢复等关键场景下。尽管 PyTorch 原生支持 Fully Sharded Data Parallelism (FSDP) 策略，但 DLRover 作为一个天然的弹性训练系统，当面临动态的资源扩缩容和容错场景时，简单的使用 PyTorch
一行太长了，尽量保证每行不要超过80个字。整个文档统一修改下。

2023-08-29 23:24 UTC, merlintang commented
for open source project, can we translate this doc to English? @Major-333

2023-08-30 03:15 UTC, Major-333 commented
> for open source project, can we translate this doc to English? @Major-333

OK

2023-08-30 07:57 UTC, Major-333 commented on docs/design/fsdp-design.md
> +随着大规模机器学习模型的持续增长，分布式训练已经成为该领域的核心技术。DLRover 系统已展现出其在多个方面的优势，特别是在节点故障、资源动态分配和自动恢复等关键场景下。尽管 PyTorch 原生支持 Fully Sharded Data Parallelism (FSDP) 策略，但 DLRover 作为一个天然的弹性训练系统，当面临动态的资源扩缩容和容错场景时，简单的使用 PyTorch
Done

2023-08-31 06:50 UTC, workingloong approved these changes
LGTM

2023-09-12 10:52 UTC, merlintang commented
LGTM

2023-09-12 10:52 UTC, merlintang approved these changes

2023-09-12 10:54 UTC, merlintang commented
let us merge this pr into https://github.com/intelligent-machine-learning/dlrover/pull/644

2023-10-12 06:26 UTC, workingloong commented
Close it because it is outdated.

2023-10-12 06:26 UTC, closed without merging